In [4]:
from pprint import pprint

In [1]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [7]:
#1.10.1
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
inc=inc.T
pprint(inc)

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])


In [8]:
#1.10.2
cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption])
cons = cons.T
pprint(cons)

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])


In [9]:
#1.10.3
pprint(inc*0.87)

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])


In [12]:
#1.10.4
P = inc*0.87 - cons
pprint(P)

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])
